#!/usr/bin/env bash

print_style () {
    if [ "$2" == "info" ] ; then
        COLOR="96m"
    elif [ "$2" == "success" ] ; then
        COLOR="92m"
    elif [ "$2" == "warning" ] ; then
        COLOR="93m"
    elif [ "$2" == "danger" ] ; then
        COLOR="91m"
    else #default color
        COLOR="0m"
    fi

    STARTCOLOR="\e[$COLOR"
    ENDCOLOR="\e[0m"

    printf "$STARTCOLOR%b$ENDCOLOR" "$1"
}

display_options () {
    printf "Available options:\n";
    print_style "   go api (alias ga)" "info"; printf "\t Enter workspace with laradock user and moved to api\n"
}

go_to () {
    cc="${dcm} -w ${cws}/$1 ${ctn} bash"
    print_style "Run: ${cc}\n" "info"
    ${cc}
}

show_ngrok () {
    curl -s $(docker port concrete_ngrok_1 4040)/api/tunnels/command_line | python -c "import sys, json; print json.load(sys.stdin)['public_url']"
}

cws="/var/www"
ctn="concrete_workspace_1"
dcm="docker exec -it -u laradock"

case $1 in
    go)
        case $2 in
            api)
                go_to "concrete-api"
                ;;
        esac
        ;;
    ga)
        go_to "concrete-api"
        ;;
    gac)
        go_to "concrete-api-crawler"
        ;;
    ngrok)
        show_ngrok
        ;;
    *)
        display_options
        ;;
esac

